import { StyleSheet } from "react-native";
import { colors } from "@/constants/colors";

export const jakarta = {
  regular: "PlusJakartaSans_400Regular",
  medium: "PlusJakartaSans_500Medium",
  semiBold: "PlusJakartaSans_600SemiBold",
  bold: "PlusJakartaSans_700Bold",
  extraBold: "PlusJakartaSans_800ExtraBold"
};

export const styles = StyleSheet.create({
  appContent: { flex: 1 },
  appContentWithTabs: { flex: 1, paddingBottom: 88 },
  splash: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.white, overflow: "hidden", gap: 18 },
  splashBand: { position: "absolute", left: 0, right: 0, height: 214 },
  topBand: { top: 0 },
  bottomBand: { bottom: 0 },
  splashTopWave: { position: "absolute", top: 126, left: 0, right: 0 },
  splashBottomWave: { position: "absolute", bottom: 0, left: 0, right: 0 },
  fallingRupee: { position: "absolute", color: colors.gold, fontWeight: "900", textShadowColor: "rgba(255,213,74,0.5)", textShadowRadius: 9, zIndex: 2 },
  hindiTitle: { fontSize: 52, color: colors.navy, fontWeight: "900", letterSpacing: 0 },
  hindiTitleSmall: { fontSize: 42, color: colors.navy, fontWeight: "900", letterSpacing: 0 },
  hindiHero: { fontSize: 44, color: colors.white, fontWeight: "900", letterSpacing: 0, marginTop: 12 },
  schemeBadge: { paddingHorizontal: 18, paddingVertical: 9, borderRadius: 999, backgroundColor: colors.gold },
  schemeBadgeText: { color: colors.navy, fontWeight: "900" },
  powered: { position: "absolute", bottom: 38, color: colors.muted, fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  authHero: { alignItems: "center", paddingTop: 42, paddingBottom: 22, gap: 10 },
  authCopy: { color: colors.muted, fontWeight: "800" },
  loadingSafe: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.background, padding: 24 },
  loadingCard: {
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 26,
    paddingVertical: 24,
    borderRadius: 24,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border
  },
  loadingTitle: { color: colors.navy, fontWeight: "700", fontSize: 14, textAlign: "center" },
  emptyState: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, gap: 14 },
  emptyTitle: { color: colors.navy, fontWeight: "700", fontSize: 20, textAlign: "center" },
  emptyText: { color: colors.muted, fontWeight: "600", fontSize: 12, textAlign: "center", lineHeight: 20 },
  emptyInlineText: { color: colors.muted, fontWeight: "600", fontSize: 11, textAlign: "center", paddingVertical: 14 },
  homeSafe: { flex: 1, backgroundColor: colors.background },
  homeScroll: { flex: 1 },
  homeScrollContent: { flexGrow: 1, paddingBottom: 30 },
  homeTopBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 22, paddingTop: 12, paddingBottom: 18 },
  homeIconButton: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#e7edf4",
    shadowColor: colors.navy,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4
  },
  homeMenuIcon: { color: colors.navy, fontSize: 26, fontWeight: "700" },
  bellIcon: { fontSize: 24 },
  homeBrand: { flexDirection: "row", alignItems: "center", gap: 10 },
  homeBrandText: { color: colors.navy, fontWeight: "700", fontSize: 22, letterSpacing: 0 },
  homePage: { paddingHorizontal: 20, gap: 16 },
  greetingBlock: { marginTop: 10 },
  greetingMuted: { color: colors.muted, fontWeight: "700", fontSize: 15 },
  greetingName: { color: colors.navy, fontWeight: "700", fontSize: 29, letterSpacing: 0, marginTop: 2 },
  greetingJi: { color: colors.cyan },
  redeemHero: {
    minHeight: 256,
    borderRadius: 30,
    padding: 30,
    overflow: "hidden",
    shadowColor: colors.primary,
    shadowOpacity: 0.25,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 16 },
    elevation: 10
  },
  heroRingOuter: { position: "absolute", right: -28, top: -6, width: 132, height: 132, borderRadius: 66, borderWidth: 3, borderColor: "rgba(255,255,255,0.18)" },
  heroRingInner: { position: "absolute", right: 28, top: 30, width: 58, height: 58, borderRadius: 29, backgroundColor: "rgba(255,255,255,0.08)" },
  redeemEyebrow: { color: "rgba(255,255,255,0.78)", fontWeight: "700", fontSize: 13, letterSpacing: 3 },
  redeemAmount: { color: colors.white, fontWeight: "700", fontSize: 53, letterSpacing: 0, marginTop: 8 },
  redeemCopy: { color: "rgba(255,255,255,0.88)", fontWeight: "700", fontSize: 14 },
  redeemButton: { marginTop: 24, height: 66, borderRadius: 20, backgroundColor: colors.white, alignItems: "center", justifyContent: "center" },
  redeemButtonText: { color: colors.primary, fontWeight: "700", fontSize: 15, letterSpacing: 2 },
  walletSectionHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 8 },
  walletSectionTitle: { color: colors.navy, fontWeight: "700", fontSize: 19 },
  walletSectionMeta: { color: colors.muted, fontWeight: "700", fontSize: 12 },
  homeWalletCard: {
    borderRadius: 28,
    padding: 24,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#dce7f0",
    shadowColor: colors.navy,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5
  },
  boosterHomeCard: { backgroundColor: "#fffdf4" },
  homeWalletHeader: { flexDirection: "row", alignItems: "center", gap: 14 },
  walletIconBox: { width: 52, height: 52, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#e8f4ff" },
  boosterIconBox: { backgroundColor: "#fff3ce" },
  walletIconText: { fontSize: 24 },
  homeWalletTitle: { color: colors.navy, fontWeight: "700", fontSize: 16 },
  homeWalletSubtitle: { color: colors.muted, fontWeight: "600", fontSize: 11, marginTop: 2 },
  homeWalletAmount: { color: colors.primary, fontWeight: "700", fontSize: 38, letterSpacing: 0, marginTop: 18 },
  homeWalletRate: { color: colors.muted, fontSize: 11, fontWeight: "700" },
  achievementText: { color: colors.muted, fontWeight: "700", fontSize: 10, marginTop: 4 },
  slabProgressBlock: { marginTop: 14, paddingTop: 7 },
  slabTrack: { height: 7, borderRadius: 99, backgroundColor: "#edf2f6", position: "relative" },
  slabTrackFill: { position: "absolute", left: 0, top: 0, bottom: 0, borderRadius: 99, backgroundColor: colors.primary },
  boosterTrackFill: { backgroundColor: "#d99a00" },
  slabProgressRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 8 },
  slabRateText: { color: "#8da0af", fontWeight: "700", fontSize: 8 },
  slabRateActive: { color: colors.primary },
  boosterRateActive: { color: "#c88a00" },
  currentSlabDot: { position: "absolute", top: -7, marginLeft: -11, width: 22, height: 22, borderRadius: 11, backgroundColor: colors.white, borderWidth: 3, borderColor: colors.primary },
  boosterProgressDot: { borderColor: "#d99a00" },
  nextSlabBox: { flexDirection: "row", gap: 14, alignItems: "center", marginTop: 16, padding: 16, borderRadius: 18, borderWidth: 1.5, borderStyle: "dashed", borderColor: "#a7d4f2", backgroundColor: "#f2f8ff" },
  nextBoosterBox: { borderColor: "#ffe0a1", backgroundColor: "#fffaf0" },
  targetIcon: { width: 48, height: 48, borderRadius: 14, backgroundColor: colors.white, alignItems: "center", justifyContent: "center" },
  targetIconText: { fontSize: 22 },
  nextSlabTitle: { color: colors.primary, fontWeight: "700", fontSize: 14 },
  nextBoosterTitle: { color: "#c88a00" },
  nextSlabMeta: { color: colors.muted, fontWeight: "600", fontSize: 10, marginTop: 6 },
  openWalletButton: { height: 48, borderRadius: 16, backgroundColor: "#e8f4ff", borderWidth: 1.5, borderColor: "#a7d4f2", alignItems: "center", justifyContent: "center", marginTop: 20 },
  openBoosterButton: { height: 48, borderRadius: 16, backgroundColor: "#fff7d6", borderWidth: 1.5, borderColor: "#ffe59a", alignItems: "center", justifyContent: "center", marginTop: 18 },
  openWalletText: { color: colors.primary, fontWeight: "700", fontSize: 13, letterSpacing: 0.5 },
  boosterAmount: { color: "#c88a00", fontWeight: "700", fontSize: 32, marginTop: 18 },
  homeTabs: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 88,
    paddingHorizontal: 12,
    paddingTop: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.96)",
    borderTopWidth: 1,
    borderColor: colors.border
  },
  homeTabItem: { width: 64, alignItems: "center", gap: 4 },
  homeTabIcon: { fontSize: 22 },
  homeTabActive: { color: colors.primary, fontWeight: "700", fontSize: 10 },
  homeTabText: { color: "#93a1af", fontWeight: "700", fontSize: 10 },
  redeemFab: { width: 82, alignItems: "center", marginTop: -34 },
  redeemFabText: { width: 78, height: 78, borderRadius: 39, textAlign: "center", lineHeight: 78, overflow: "hidden", color: colors.gold, fontWeight: "700", fontSize: 36, backgroundColor: colors.primary },
  redeemFabTextActive: { backgroundColor: colors.navy },
  redeemFabLabel: { color: colors.primary, fontWeight: "700", fontSize: 10, marginTop: 4 },
  redeemFabLabelActive: { color: colors.navy, fontWeight: "700", fontSize: 10, marginTop: 4 },
  walletDetailSafe: { flex: 1, backgroundColor: "#f3f7fa" },
  walletDetailGoldSafe: { backgroundColor: "#fffaf0" },
  walletDetailScrollView: { flex: 1 },
  walletDetailScroll: { flexGrow: 1, paddingBottom: 120 },
  walletDetailHero: { minHeight: 372, paddingHorizontal: 28, paddingTop: 15, alignItems: "center", overflow: "hidden", borderBottomLeftRadius: 0, borderBottomRightRadius: 0 },
  walletHeroGreen: { shadowColor: colors.primary },
  walletHeroGold: { shadowColor: "#d4a000" },
  walletDetailTopRow: { width: "100%", flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 4 },
  walletHeroIcon: { width: 44, height: 44, borderRadius: 15, borderWidth: 1.5, borderColor: "rgba(255,255,255,0.42)", backgroundColor: "rgba(255,255,255,0.16)", alignItems: "center", justifyContent: "center" },
  walletHeroIconText: { fontFamily: jakarta.semiBold, color: colors.white, fontSize: 19 },
  walletHeroInfo: { fontFamily: jakarta.semiBold, color: colors.white, fontSize: 19 },
  walletDetailTitle: { fontFamily: jakarta.semiBold, color: colors.white, fontSize: 13, letterSpacing: 4, textAlign: "center" },
  walletHeroPill: { marginTop: 20, paddingHorizontal: 20, height: 32, borderRadius: 999, borderWidth: 1.5, borderColor: "rgba(255,255,255,0.45)", backgroundColor: "rgba(255,255,255,0.16)", alignItems: "center", justifyContent: "center" },
  walletHeroPillText: { fontFamily: jakarta.semiBold, color: colors.white, fontSize: 8, letterSpacing: 1.6, textTransform: "uppercase" },
  walletHeroLabel: { fontFamily: jakarta.semiBold, color: colors.white, fontSize: 11, letterSpacing: 3.6, marginTop: 20 },
  walletHeroAmount: { fontFamily: jakarta.semiBold, color: colors.white, fontSize: 51, letterSpacing: 0, marginTop: 2 },
  walletHeroSub: { fontFamily: jakarta.semiBold, color: colors.white, fontSize: 11, textAlign: "center" },
  walletHeroWave: { position: "absolute", left: -80, right: -80, bottom: -54, height: 120, borderTopLeftRadius: 240, borderTopRightRadius: 240, backgroundColor: "#f8fafc", transform: [{ rotate: "-4deg" }] },
  walletHeroWaveSvg: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: -1,
  },
  walletDetailBody: { paddingHorizontal: 18, marginTop: -26, gap: 18 },
  detailStatsCard: { flexDirection: "row", borderRadius: 22, backgroundColor: colors.white, borderWidth: 1, borderColor: "#dce7f0", paddingVertical: 14, shadowColor: colors.navy, shadowOpacity: 0.08, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 4 },
  detailStat: { flex: 1, alignItems: "center", borderRightWidth: 1, borderRightColor: "#e6edf4", minHeight: 46, justifyContent: "center" },
  detailStatLabel: { fontFamily: jakarta.semiBold, color: "#9aa7b5", fontSize: 7, letterSpacing: 1.8 },
  detailStatValue: { fontFamily: jakarta.semiBold, fontSize: 12, marginTop: 5 },
  expiryNotice: { flexDirection: "row", gap: 12, padding: 14, borderRadius: 20, borderWidth: 1.5, borderStyle: "dashed", borderColor: "#ffb8b8", backgroundColor: "#fff6f6", alignItems: "center" },
  expiryIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: colors.white, alignItems: "center", justifyContent: "center" },
  expiryIconText: { fontSize: 21 },
  expiryTitle: { fontFamily: jakarta.semiBold, color: colors.danger, fontSize: 13 },
  expiryText: { fontFamily: jakarta.medium, color: colors.muted, fontSize: 9, lineHeight: 17, marginTop: 3 },
  detailDividerRow: { flexDirection: "row", alignItems: "center", gap: 14, marginTop: 2 },
  detailDividerTitle: { fontFamily: jakarta.semiBold, color: colors.muted, letterSpacing: 3.6, fontSize: 10 },
  detailDividerLine: { flex: 1, height: 1, backgroundColor: "#d7e1eb" },
  slabJourneyCard: { borderRadius: 24, borderWidth: 1, borderColor: "#dce7f0", backgroundColor: "#f8fbff", padding: 18, overflow: "hidden" },
  slabJourneyHeader: { flexDirection: "row", gap: 14, alignItems: "center", marginBottom: 14 },
  slabJourneyIcon: { width: 50, height: 50, borderRadius: 16, backgroundColor: "#e8f4ff", alignItems: "center", justifyContent: "center" },
  slabJourneyIconText: { fontSize: 22 },
  slabJourneyTitle: { fontFamily: jakarta.semiBold, color: colors.navy, fontSize: 14 },
  slabJourneySub: { fontFamily: jakarta.medium, color: colors.muted, fontSize: 10, marginTop: 2 },
  ladderWrap: { gap: 0 },
  ladderRow: { flexDirection: "row", minHeight: 78 },
  ladderRail: { width: 70, alignItems: "center" },
  ladderCircle: { width: 48, height: 48, borderRadius: 24, borderWidth: 1.5, borderColor: "#e3eaf1", backgroundColor: "rgba(255,255,255,0.75)", alignItems: "center", justifyContent: "center" },
  ladderCircleReached: { borderColor: "#9fcfec", backgroundColor: "#eef7ff" },
  ladderCircleActive: { borderColor: colors.primary, borderWidth: 3, backgroundColor: colors.white },
  ladderCircleText: { fontFamily: jakarta.semiBold, color: "#b2bfca", fontSize: 11 },
  ladderCircleActiveText: { color: colors.primary },
  ladderLine: { width: 5, flex: 1, backgroundColor: "#e8f2fb" },
  ladderLineReached: { backgroundColor: "#bddbf2" },
  ladderContent: { flex: 1, paddingTop: 2 },
  ladderTitleRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  ladderReward: { fontFamily: jakarta.semiBold, color: "#aeb8c3", fontSize: 16 },
  ladderRewardActive: { color: colors.primary },
  ladderRange: { fontFamily: jakarta.semiBold, color: "#7f8fa0", fontSize: 10, marginTop: 2 },
  ladderTierName: { fontFamily: jakarta.medium, color: colors.muted, fontSize: 8, marginTop: 2 },
  nextPill: { fontFamily: jakarta.semiBold, color: colors.primary, fontSize: 7, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, borderWidth: 1, borderStyle: "dashed", borderColor: "#a7d4f2", backgroundColor: "#f2f8ff" },
  detailSectionHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 2 },
  inlineTitleWrap: { flexDirection: "row", alignItems: "center", gap: 10 },
  detailSectionTitle: { fontFamily: jakarta.semiBold, color: colors.navy, fontSize: 14 },
  liveBadge: { fontFamily: jakarta.semiBold, color: colors.primary, backgroundColor: "#e8f4ff", borderWidth: 1, borderColor: "#a7d4f2", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, fontSize: 9 },
  viewAllLink: { fontFamily: jakarta.semiBold, color: colors.blue, fontSize: 10 },
  boosterSchemeCard: { borderRadius: 24, padding: 20, backgroundColor: colors.white, borderWidth: 1, borderColor: "#eadcae", shadowColor: "#d4a000", shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 4 },
  boosterSchemeTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  boosterSchemeIcon: { width: 54, height: 54, borderRadius: 18, borderWidth: 1.5, borderColor: "#eadcae", backgroundColor: "#fffdf6", alignItems: "center", justifyContent: "center" },
  boosterSchemeIconText: { fontSize: 22 },
  boosterSchemeTitle: { fontFamily: jakarta.semiBold, color: colors.navy, fontSize: 16, marginTop: 16 },
  boosterSchemeSub: { fontFamily: jakarta.semiBold, color: colors.muted, fontSize: 10, marginTop: 5 },
  boosterEarnBox: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16, borderRadius: 18, borderWidth: 1.4, borderStyle: "dashed", borderColor: "#eadcae", backgroundColor: "#fffdf7", marginTop: 20 },
  boosterEarnLabel: { fontFamily: jakarta.semiBold, color: colors.muted, fontSize: 8, letterSpacing: 1.8 },
  boosterEarnValue: { fontFamily: jakarta.semiBold, color: "#d4a000", fontSize: 23, marginTop: 4 },
  boosterUnits: { fontFamily: jakarta.semiBold, color: colors.navy, fontSize: 21, marginTop: 4 },
  boosterDateRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 20 },
  boosterDateText: { fontFamily: jakarta.semiBold, color: colors.muted, fontSize: 9 },
  boosterElapsedText: { fontFamily: jakarta.semiBold, color: "#a97900", fontSize: 9 },
  boosterElapsedTrack: { height: 10, borderRadius: 999, backgroundColor: "#edf2f6", overflow: "hidden", marginTop: 10 },
  boosterElapsedFill: { height: "100%", borderRadius: 999, backgroundColor: "#ddb111" },
  boosterDots: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8, marginTop: -8 },
  boosterDotActive: { width: 34, height: 10, borderRadius: 999, backgroundColor: "#d4a000" },
  boosterDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: "#e5ebf1" },
  lifetimeCard: { borderRadius: 24, padding: 18, backgroundColor: "#fffef8", borderWidth: 1, borderColor: "#dce7f0" },
  lifetimeHeader: { flexDirection: "row", alignItems: "center", gap: 14 },
  lifetimeIcon: { width: 50, height: 50, borderRadius: 16, backgroundColor: "#fff5d6", alignItems: "center", justifyContent: "center" },
  lifetimeIconText: { fontFamily: jakarta.semiBold, color: colors.navy, fontSize: 18 },
  lifetimeTitle: { fontFamily: jakarta.semiBold, color: colors.navy, fontSize: 14 },
  lifetimeSub: { fontFamily: jakarta.medium, color: colors.muted, fontSize: 10 },
  lifetimeGrid: { flexDirection: "row", gap: 12, marginTop: 18 },
  miniSummary: { flex: 1, minHeight: 94, borderRadius: 18, padding: 14, backgroundColor: "#fff7d6", borderWidth: 1, borderColor: "#eadcae" },
  miniSummaryBlue: { backgroundColor: "#eef8ff", borderColor: "#bfe0f7" },
  miniSummaryTitle: { fontFamily: jakarta.semiBold, color: "#a97900", fontSize: 7, letterSpacing: 1.3 },
  miniSummaryBlueText: { color: colors.blue },
  miniSummaryValue: { fontFamily: jakarta.semiBold, color: "#d4a000", fontSize: 21, marginTop: 8 },
  timelineCard: { borderRadius: 20, backgroundColor: colors.white, borderWidth: 1, borderColor: "#dce7f0", overflow: "hidden" },
  timelineRow: { flexDirection: "row", gap: 12, alignItems: "center", padding: 14, borderBottomWidth: 1, borderBottomColor: "#edf2f6" },
  timelineDot: { width: 11, height: 11, borderRadius: 6 },
  timelineTitle: { fontFamily: jakarta.semiBold, color: colors.navy, fontSize: 10 },
  timelineSub: { fontFamily: jakarta.medium, color: colors.muted, fontSize: 8, marginTop: 3 },
  timelineAmount: { fontFamily: jakarta.semiBold, fontSize: 11 },
  walletStickyWrap: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 22, paddingTop: 16, paddingBottom: 26, backgroundColor: "rgba(255,255,255,0.92)" },
  walletStickyButton: { height: 62, borderRadius: 22, shadowColor: colors.navy, shadowOpacity: 0.16, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  walletStickyPress: { flex: 1, alignItems: "center", justifyContent: "center" },
  walletStickyText: { fontFamily: jakarta.semiBold, color: colors.white, fontSize: 14, letterSpacing: 1.2 },
  authKeyboardAvoiding: { flex: 1 },
  authSafe: { flex: 1, backgroundColor: "#f8fafc" },
  authPhone: { flex: 1, minHeight: 720, overflow: "hidden" },
  authTopGradient: { position: "absolute", top: 0, left: 0, right: 0, height: 268 },
  authTopWave: { position: "absolute", top: 132, left: 0, right: 0 },
  authDotGrid: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0 },
  authBottomGradient: { position: "absolute", left: 0, right: 0, bottom: 0, height: 176 },
  authBottomWave: { position: "absolute", left: 0, right: 0, bottom: 0 },
  authBackButton: { position: "absolute", top: 84, left: 34, zIndex: 6, width: 48, height: 48, borderRadius: 14, borderWidth: 1.4, borderColor: "rgba(255,255,255,0.42)", backgroundColor: "rgba(255,255,255,0.16)", alignItems: "center", justifyContent: "center" },
  authBackText: { color: colors.white, fontFamily: jakarta.extraBold, fontSize: 22, marginTop: -2 },
  authLogoCircle: { backgroundColor: colors.white, alignItems: "center", justifyContent: "center", shadowColor: colors.navy, shadowOpacity: 0.09, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 5 },
  authHeroBlock: { position: "absolute", top: 58, left: 0, right: 0, zIndex: 4, alignItems: "center" },
  authHeroBrand: { top: 58 },
  authHeroVerify: { top: 94 },
  authHindiTitle: { marginTop: 19, fontFamily: jakarta.extraBold, color: colors.white, fontSize: 30, lineHeight: 36, textAlign: "center" },
  authRewards: { marginTop: 1, fontFamily: jakarta.extraBold, color: "rgba(255,255,255,0.9)", fontSize: 12, letterSpacing: 6 },
  authHeroTitle: { marginTop: 17, fontFamily: jakarta.extraBold, color: colors.white, fontSize: 14, letterSpacing: 7, textAlign: "center" },
  authBody: { flex: 1, justifyContent: "center", paddingHorizontal: 26, paddingTop: 150, paddingBottom: 118, zIndex: 2 },
  authCard: { width: "100%", maxWidth: 400, alignSelf: "center", borderRadius: 24, backgroundColor: colors.white, paddingHorizontal: 26, paddingTop: 30, paddingBottom: 29, shadowColor: colors.navy, shadowOpacity: 0.11, shadowRadius: 24, shadowOffset: { width: 0, height: 16 }, elevation: 7 },
  loginAuthBody: { paddingHorizontal: 26, paddingTop: 150, paddingBottom: 112 },
  loginAuthCard: { maxWidth: 342, borderRadius: 28, paddingHorizontal: 26, paddingTop: 28, paddingBottom: 26 },
  loginAuthCardTitle: { fontSize: 22, lineHeight: 29 },
  loginAuthDescription: { fontSize: 12.5, lineHeight: 19, marginTop: 7 },
  loginAuthMobileInput: { height: 54, borderRadius: 16 },
  loginAuthButton: { height: 50, borderRadius: 15, marginTop: 24 },
  authWelcomeBadge: { alignSelf: "flex-start", height: 26, paddingHorizontal: 13, borderRadius: 999, backgroundColor: "#e8f4ff", alignItems: "center", justifyContent: "center", marginBottom: 19 },
  authWelcomeText: { fontFamily: jakarta.extraBold, color: colors.primary, fontSize: 10.5, letterSpacing: 1.8 },
  authChangeMobileButton: { position: "relative", zIndex: 20, elevation: 20, alignSelf: "stretch", minHeight: 44, flexDirection: "row", alignItems: "center", paddingRight: 12, marginBottom: 8 },
  authChangeMobileIcon: { fontFamily: jakarta.extraBold, color: colors.blue, fontSize: 28, lineHeight: 30, marginRight: 5 },
  authChangeMobileText: { fontFamily: jakarta.extraBold, color: colors.blue, fontSize: 12 },
  authCardTitle: { fontFamily: jakarta.extraBold, color: colors.navy, fontSize: 23, lineHeight: 30 },
  authDescription: { marginTop: 5, fontFamily: jakarta.medium, color: colors.muted, fontSize: 12, lineHeight: 20 },
  authLabel: { marginTop: 20, marginBottom: 9, fontFamily: jakarta.extraBold, color: "#405064", fontSize: 10.5, letterSpacing: 2.4 },
  authMobileInput: { height: 64, borderRadius: 18, borderWidth: 2, borderColor: "#dce6ee", backgroundColor: "#f9fbfd", flexDirection: "row", alignItems: "center", paddingHorizontal: 15, overflow: "hidden" },
  authInputActive: { borderColor: "#bfd9ea" },
  authCountrySegment: { position: "absolute", left: 0, top: 0, bottom: 0, width: 106, backgroundColor: "#eef7ff" },
  authFlag: { fontSize: 20, marginRight: 9, zIndex: 1 },
  authDialCode: { fontFamily: jakarta.extraBold, color: colors.navy, fontSize: 18, marginRight: 15, zIndex: 1 },
  authInputDivider: { width: 1, height: 30, backgroundColor: "#dfe8ef", marginRight: 17, zIndex: 1 },
  authMobileTextInput: { flex: 1, height: "100%", padding: 0, fontFamily: jakarta.extraBold, color: colors.navy, fontSize: 17.5, letterSpacing: 0 },
  authTextInput: { height: 54, borderRadius: 16, borderWidth: 2, borderColor: "#dce6ee", backgroundColor: "#f9fbfd", paddingHorizontal: 16, fontFamily: jakarta.bold, color: colors.navy, fontSize: 15 },
  authPasswordInput: { height: 54, borderRadius: 16, borderWidth: 2, borderColor: "#dce6ee", backgroundColor: "#f9fbfd", flexDirection: "row", alignItems: "center" },
  authPasswordTextInput: { flex: 1, height: "100%", paddingLeft: 16, paddingRight: 8, fontFamily: jakarta.bold, color: colors.navy, fontSize: 15 },
  authPasswordEye: { width: 48, height: "100%", alignItems: "center", justifyContent: "center" },
  authPasswordEyeText: { fontFamily: jakarta.extraBold, color: colors.blue, fontSize: 24 },
  authForgotLink: { marginTop: 12, alignSelf: "flex-end", fontFamily: jakarta.extraBold, color: colors.blue, fontSize: 12 },
  authTestingNotice: { marginTop: 20, padding: 16, borderRadius: 16, backgroundColor: "#fff7df", borderWidth: 1, borderColor: "#f0cf70", gap: 14 },
  authTestingNoticeText: { fontFamily: jakarta.medium, color: colors.navy, fontSize: 12, lineHeight: 19 },
  authTestingLink: { fontFamily: jakarta.extraBold, color: colors.blue, fontSize: 13, textAlign: "center", textDecorationLine: "underline" },
  authCancelButton: { marginTop: 12, height: 48, borderRadius: 15, borderWidth: 2, borderColor: colors.blue, backgroundColor: colors.white, alignItems: "center", justifyContent: "center", zIndex: 20, elevation: 4 },
  authCancelButtonText: { fontFamily: jakarta.extraBold, color: colors.blue, fontSize: 13, letterSpacing: 1.8 },
  authCounter: { marginTop: 7, fontFamily: jakarta.bold, color: "#a4afbb", fontSize: 11.5 },
  authButton: { marginTop: 30, height: 58, borderRadius: 16, backgroundColor: "#148fc2", alignItems: "center", justifyContent: "center", shadowColor: colors.navy, shadowOpacity: 0.06, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 2 },
  authButtonDisabled: { backgroundColor: "#cbd5df" },
  authButtonText: { fontFamily: jakarta.extraBold, color: colors.white, fontSize: 14.5, letterSpacing: 2.1 },
  authTerms: { marginTop: 20, textAlign: "center", fontFamily: jakarta.medium, color: "#96a1ae", fontSize: 10.3, lineHeight: 15 },
  authTermsLink: { fontFamily: jakarta.extraBold, color: colors.blue },
  authFooterContent: { position: "absolute", left: 20, right: 20, bottom: 25, zIndex: 4, alignItems: "center" },
  authHelpText: { fontFamily: jakarta.extraBold, color: colors.white, fontSize: 11 },
  authHelpLink: { textDecorationLine: "underline" },
  otpCard: { paddingTop: 14, paddingBottom: 34, marginTop: 22 },
  authChatIcon: { width: 58, height: 58, borderRadius: 17, backgroundColor: "#dff0ff", alignItems: "center", justifyContent: "center", marginBottom: 14 },
  authChatText: { color: colors.navy, fontFamily: jakarta.extraBold, fontSize: 28, transform: [{ rotate: "180deg" }] },
  otpCardTitle: { fontFamily: jakarta.extraBold, color: colors.navy, fontSize: 22, lineHeight: 20 },
  otpDescription: { marginTop: 8, fontFamily: jakarta.medium, color: colors.muted, fontSize: 12, lineHeight: 15 },
  otpMobile: { fontFamily: jakarta.extraBold, color: colors.navy },
  otpChangeText: { marginTop: 2, fontFamily: jakarta.extraBold, color: colors.blue, fontSize: 14 },
  hiddenOtpInput: { position: "absolute", width: 1, height: 1, opacity: 0 },
  resendWrap: { alignItems: "center", marginTop: 25 },
  resendText: { fontFamily: jakarta.medium, color: colors.muted, fontSize: 13 },
  resendTimer: { fontFamily: jakarta.extraBold, color: colors.navy },
  authSecureBadge: { height: 30, paddingHorizontal: 18, borderRadius: 999, borderWidth: 1.2, borderColor: "rgba(255,255,255,0.36)", backgroundColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" },
  authSecureText: { fontFamily: jakarta.extraBold, color: colors.white, fontSize: 11 },
  successAuthBody: { flex: 1, alignItems: "center", justifyContent: "center", paddingTop: 100, paddingBottom: 72 },
  successRingMid: { width: 158, height: 158, borderRadius: 79, backgroundColor: "rgba(21,89,154,0.09)", alignItems: "center", justifyContent: "center" },
  successTitle: { marginTop: 26, fontFamily: jakarta.extraBold, color: colors.navy, fontSize: 27, textAlign: "center" },
  successSubtitle: { marginTop: 8, fontFamily: jakarta.medium, color: colors.muted, fontSize: 16, textAlign: "center" },
  successChecklist: { marginTop: 34, gap: 18, alignSelf: "center", minWidth: 240 },
  successItem: { flexDirection: "row", alignItems: "center", gap: 14 },
  successDoneIcon: { width: 26, height: 26, borderRadius: 13, overflow: "hidden", backgroundColor: colors.primary, color: colors.white, fontFamily: jakarta.extraBold, textAlign: "center", lineHeight: 26 },
  successDoneText: { fontFamily: jakarta.extraBold, color: colors.primary, fontSize: 15 },
  successLoadingIcon: { width: 30, height: 30, borderRadius: 15, borderWidth: 3, borderColor: colors.primary, alignItems: "center", justifyContent: "center" },
  successLoadingDot: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: "rgba(21,89,154,0.25)" },
  successLoadingText: { fontFamily: jakarta.extraBold, color: colors.navy, fontSize: 15 },
  successDots: { position: "absolute", bottom: 2, flexDirection: "row", gap: 8 },
  successDotActive: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.white },
  successDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: "rgba(255,255,255,0.34)" },
  panel: { margin: 18, padding: 18, borderRadius: 24, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, gap: 16 },
  panelFlat: { padding: 16, borderRadius: 20, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, gap: 8 },
  panelTitle: { color: colors.navy, fontWeight: "700", fontSize: 22, letterSpacing: 0 },
  mobileRow: { gap: 12 },
  codeBox: { height: 54, paddingHorizontal: 18, borderRadius: 16, backgroundColor: colors.successSoft, alignSelf: "flex-start", alignItems: "center", justifyContent: "center" },
  codeText: { color: colors.primary, fontWeight: "700", fontSize: 14 },
  tick: { color: colors.primary, fontWeight: "700", fontSize: 18 },
  otpRow: { flexDirection: "row", gap: 12, marginTop: 26 },
  otpBox: { flex: 1, height: 76, borderRadius: 14, backgroundColor: "#f8fafc", borderWidth: 2, borderColor: "#dce6ee", alignItems: "center", justifyContent: "center" },
  otpBoxFilled: { borderColor: "#a7cfdd", backgroundColor: colors.white },
  otpText: { fontFamily: jakarta.extraBold, fontSize: 25, color: colors.navy },
  testingOtp: { color: colors.primary, fontWeight: "900", textAlign: "center" },
  linkText: { color: colors.blue, fontWeight: "900", textAlign: "center" },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 18 },
  successRing: { width: 180, height: 180, borderRadius: 90, backgroundColor: "rgba(21,89,154,0.06)", alignItems: "center", justifyContent: "center", shadowColor: colors.primary, shadowOpacity: 0.18, shadowRadius: 24, shadowOffset: { width: 0, height: 12 }, elevation: 7 },
  successCircle: { width: 132, height: 132, borderRadius: 66, alignItems: "center", justifyContent: "center" },
  successCheck: { color: colors.white, fontWeight: "900", fontSize: 56 },
  successCheckGreen: { color: colors.primary, fontWeight: "700", fontSize: 56, textAlign: "center" },
  stepText: { color: colors.primary, fontWeight: "700", fontSize: 10, textTransform: "uppercase" },
  helperText: { color: colors.muted, fontWeight: "700", lineHeight: 20 },
  pagePad: { paddingHorizontal: 18, gap: 16, paddingBottom: 10 },
  heroLabel: { color: "rgba(255,255,255,0.78)", fontWeight: "700", fontSize: 10, textTransform: "uppercase" },
  heroAmount: { color: colors.white, fontWeight: "700", fontSize: 36, letterSpacing: 0, marginTop: 8 },
  heroSub: { color: "rgba(255,255,255,0.82)", fontWeight: "600", marginTop: 4 },
  walletGrid: { gap: 14 },
  walletTile: { borderRadius: 24, overflow: "hidden" },
  walletTitle: { color: colors.white, fontWeight: "700", fontSize: 13 },
  walletAmount: { color: colors.white, fontWeight: "700", fontSize: 27, marginTop: 12 },
  walletMeta: { color: "rgba(255,255,255,0.84)", fontWeight: "600", marginTop: 8 },
  quickGrid: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  quickTile: { flex: 1, minWidth: 104, backgroundColor: colors.white, borderColor: colors.border, borderWidth: 1, borderRadius: 18, padding: 14 },
  quickValue: { color: colors.navy, fontWeight: "700", fontSize: 18 },
  quickLabel: { color: colors.muted, fontWeight: "600", fontSize: 9, marginTop: 4 },
  sectionTitle: { color: colors.navy, fontWeight: "700", fontSize: 15, marginTop: 4 },
  activityRow: { flexDirection: "row", alignItems: "center", gap: 10, padding: 14, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 16 },
  activityAccent: { borderColor: colors.primary, backgroundColor: colors.successSoft },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary },
  activityText: { flex: 1, color: colors.text, fontWeight: "500", lineHeight: 20 },
  ctaText: { color: colors.white, fontWeight: "700", fontSize: 15 },
  formulaBox: { backgroundColor: colors.goldSoft, borderRadius: 18, padding: 15, borderWidth: 1, borderColor: "#ffe59a" },
  formulaText: { color: colors.navy, fontWeight: "700" },
  infoBanner: { backgroundColor: "#e8f4ff", borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "center", gap: 10 },
  infoText: { flex: 1, color: colors.blue, fontWeight: "700" },
  monthHeader: { color: colors.muted, fontWeight: "700", fontSize: 10, textTransform: "uppercase", marginTop: 8, marginBottom: 6 },
  invoiceRow: { flexDirection: "row", gap: 12, padding: 14, backgroundColor: colors.white, borderRadius: 18, borderWidth: 1, borderColor: colors.border },
  invoiceId: { color: colors.navy, fontWeight: "700" },
  invoiceDealer: { color: colors.muted, fontWeight: "600", marginTop: 4 },
  invoiceAmount: { color: colors.text, fontWeight: "600", marginTop: 5 },
  presetRow: { flexDirection: "row", gap: 8 },
  preset: { paddingHorizontal: 14, paddingVertical: 10, backgroundColor: colors.successSoft, borderRadius: 999 },
  presetText: { color: colors.primary, fontWeight: "700" },
  choiceGradient: { borderRadius: 18 },
  choice: { minHeight: 62, borderRadius: 18, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  choiceActive: { backgroundColor: "transparent", borderColor: "transparent" },
  choiceEmoji: { fontSize: 20 },
  choiceText: { flex: 1, color: colors.navy, fontWeight: "700", fontSize: 13 },
  choiceTick: { color: colors.white, fontWeight: "700", fontSize: 16 },
  tabs: { flexDirection: "row", backgroundColor: colors.white, borderRadius: 22, padding: 8, borderWidth: 1, borderColor: colors.border, marginTop: 6 },
  tab: { flex: 1, height: 42, alignItems: "center", justifyContent: "center" },
  tabText: { color: colors.muted, fontWeight: "700", fontSize: 9 },
  toastWrap: { position: "absolute", left: 16, right: 16, bottom: 28, zIndex: 1000 },
  toast: {
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 13,
    shadowColor: colors.navy,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10
  },
  toastText: { color: colors.white, fontWeight: "600", lineHeight: 20 }
});
